[include]
	path = aliases/amend.conf
	path = aliases/authorize-sign.conf
	path = aliases/branch-push.conf
	path = aliases/branch-rename.conf
	path = aliases/branches.conf
	path = aliases/checkout-pr.conf
	path = aliases/fixup.conf
	path = aliases/gone.conf
	path = aliases/graph.conf
	path = aliases/main.conf
	path = aliases/mine.conf
	path = aliases/rebase-main.conf
	path = aliases/recent-all.conf
	path = aliases/recent.conf
	path = aliases/ri.conf
	path = aliases/set-date.conf
	path = aliases/squash.conf
	path = aliases/subtree-add.conf
	path = aliases/subtree-pull.conf
	path = aliases/subtree-push.conf
	path = aliases/sync-date.conf
	path = aliases/unstage.conf
