[alias]
	# Show a decorated commit graph for all branches, tags, and remotes.
	# Usage: git graph
	graph = "!f() { git log --graph --branches --tags --remotes --oneline --decorate --color=always --pretty=format:'%C(auto)%h %G?%C(auto)%d %Creset%s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative | awk '{for(i=NF; i>=1; i--) if($i ~ /[*|]/) {if ($(i+2) ~ /[GUXYRE]/) {$(i+2)=\"🔑 \"} else if ($(i+2) != \"\") {$(i+2)=\"🟥 \"}; break}; print}' | less -R -F; }; f"
