[alias]
	# Show commits authored by me across branches, tags, and remotes using Git's user.name.
	# Usage: git mine
	mine = "!f() { git log --graph --branches --tags --remotes --oneline --decorate --pretty=format:'%C(auto)%h%C(auto)%d %Creset%s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=short --author=\"$(git config user.name)\"; }; f"
