[alias]
	# List local and remote branches ordered by their latest commit date.
	# Usage: git recent-all
	recent-all = "!git for-each-ref --sort=committerdate refs/heads/ refs/remotes --format='%(committerdate:short) %(refname:short) %(authorname) %(contents:subject)'"
